/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IContractWhiteList,
  IContractWhiteListInterface,
} from "../IContractWhiteList";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tockenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IContractWhiteList__factory {
  static readonly abi = _abi;
  static createInterface(): IContractWhiteListInterface {
    return new utils.Interface(_abi) as IContractWhiteListInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IContractWhiteList {
    return new Contract(address, _abi, signerOrProvider) as IContractWhiteList;
  }
}
